service: ${env:SERVICE_NAME}
package:
  exclude:
    - .env
    - .env*
    - ./**
  include:
    - handler.js
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 128  # memory usage is normally ~50mb
  versionFunctions: false
  deploymentBucket:
    name: amaysim-serverless-deployments-${env:AWS_ACCOUNT_ID}-${env:AWS_REGION}
  region: ${env:AWS_REGION}
  stage: ${env:ENV}
  stackTags:
    FRAMEWORK: serverless

plugins:
  - serverless-plugin-aws-alerts

custom:
  alerts:
    dashboards: true
    topics:
      ok: ${env:OPS_GENIE_SNS_ARN}
      alarm: ${env:OPS_GENIE_SNS_ARN}
      insufficientData: ${env:OPS_GENIE_SNS_ARN}
    definitions:
      functionErrors:
        threshold: 100  # you should typically be getting 0 errors
        period: 900  # 15m
      functionDuration:
        threshold: 500  # normal duration is <100ms
        statistic: 'p95'
        period: 1800
      functionInvocations:
        threshold: 10000  # our current peak is 1.25k, you may need to adjust this
        period: 900
    alarms:
      - functionErrors
      - functionThrottles
      - functionInvocations
      - functionDuration

functions:
  publish:
    handler: handler.handler
    environment:
      SUMO_ENDPOINT: ${env:SUMO_ENDPOINT}
      SOURCE_CATEGORY_OVERRIDE: ${env:SOURCE_CATEGORY_OVERRIDE}
      SOURCE_HOST_OVERRIDE: ${env:SOURCE_HOST_OVERRIDE}
      SOURCE_NAME_OVERRIDE: ${env:SOURCE_NAME_OVERRIDE}
  publish2:
    handler: handler.handler
    environment:
      SUMO_ENDPOINT: ${env:SUMO_ENDPOINT}
      SOURCE_CATEGORY_OVERRIDE: ${env:SOURCE_CATEGORY_OVERRIDE}
      SOURCE_HOST_OVERRIDE: ${env:SOURCE_HOST_OVERRIDE}
      SOURCE_NAME_OVERRIDE: ${env:SOURCE_NAME_OVERRIDE}

resources:
  Outputs:
    PublishLambdaFunctionArn:
      Description: The ARN for SumoLogic Lambda function
      Value:
        "Fn::GetAtt": [ PublishLambdaFunction, Arn ]
      Export: {"Name": "${env:SERVICE_NAME}-${env:ENV}-PublishLambdaArn"}
